class QuestionMov < ApplicationRecord
    has_many :game_questions, as: :question

    def self.movie_list
        ["Modern Times",
        "Back to the Future",
        "The Grand Budapest Hotel",
        "Little Miss Sunshine",
        "Hot Fuzz",
        "Some Like It Hot",
        "Groundhog Day",
        "Duck Soup",
        "O Brother, Where Art Thou?",
        "The Gold Rush",
        "Juno",
        "La La Land",
        "Shaun of the Dead",
        "Singing in the Rain",
        "Annie Hall",
        "Moonrise Kingdom",
        "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
        "The Truman Show",
        "The Graduate",
        "Monty Python and the Holy Grail",
        "The Big Lebowski",
        "Borat",
        "The Hangover",
        "Breakfast at Tiffany's",
        "Scott Pilgrim vs. the World",
        "500 Days of Summer",
        "Mary Poppins",
        "Being John Malkovich",
        "Planes, Trains and Automobiles",
        "Dead Poets Society",
        "The Breakfast Club",
        "Mrs. Doubtfire",
        "Superbad",
        "Dumb and Dumber",
        "Big",
        "Anchorman",
        "Wedding Crashers",
        "School of Rock",
        "Bruce Almighty",
        "White Chicks",
        "Meet the Parents",
        "Mrs. Doubtfire",
        "Trainwreck",
        "Zoolander",
        "Bill and Ted's Excellent Adventure",
        "The Birdcage",
        "Spy",
        "Clueless",
        "Napoleon Dynamite",
        "Old School",
        "Wayne's World",
        "Office Space",
        "Ferris Bueller's Day Off",
        "Clerks",
        "Mean Girls",
        "Trading Places",
        "This is Spinal Tap"]
    end
end
